### PR TITLE
Added href to footer links

### PR DESCRIPTION
**Pull request by SaranshBangar**
Resolves issue #44 

Description  -> Added appropriate links to the footer anchor tags

### CODE REVIEW

**Comment by SaranshBangar** [comment]
Resolves issue #44

**Comment by SaranshBangar** [comment]
@punyakrit Sir, while fixing this issue I noticed that the footer is not correctly being aligned in mobile devices screen width, moreover it should have a bit more information and another column for developers

image

Is anybody working on revamping it? If not I can create an issue and work on it

**Review by punyakrit — APPROVED** [review]

**Comment by SaranshBangar** [comment]
@punyakrit Sir, please do add the `level` label as well

**Comment by SaranshBangar** [comment]
> @punyakrit Sir, while fixing this issue I noticed that the footer is not correctly being aligned in mobile devices screen width, moreover it should have a bit more information and another column for developers
> 
> image
> 
> Is anybody working on revamping it? If not I can create an issue and work on it

And please do look into this potential issue as well sir @punyakrit

**Pull request merged**
