### PR TITLE
added input center in responsive devices

### LINKED ISSUE #198: [Bug]:  Add input center in responsive devices
### What happened?

@punyakrit 

check this out,
we can add input center where text start

image

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

### PR DESCRIPTION
**Pull request by dhruv8433**
@punyakrit 

[Bug]: Add input center in responsive devices #198

close #198

- added input center in responsive devices [inline where text begin]

image

image

### CODE REVIEW

**Comment by dhruv8433** [comment]
@punyakrit 

kindly check this and merge it

**Comment by dhruv8433** [comment]
@punyakrit

kindly check this and merge it

**Comment by dhruv8433** [comment]
@punyakrit 

please response
i completed my work please review it and merge it

**Review by punyakrit — APPROVED** [review]

**Comment by punyakrit** [comment]
chill bro i merged

**Pull request merged**
