### PR TITLE
added show more icon in mobile view

### PR DESCRIPTION
**Pull request by dhairyagothi**
i have added show more icon in mobile view

image

### CODE REVIEW

**Comment by punyakrit** [comment]
Screenshot 2024-06-09 at 12 00 40 AM
Giving error

**Comment by dhairyagothi** [comment]
> Screenshot 2024-06-09 at 12 00 40 AM
> Giving error on click

Okay i will see and update it asap

**Comment by dhairyagothi** [comment]
@punyakrit please check now i have fixed it 
please add level 2 badge

**Comment by dhairyagothi** [comment]
@punyakrit Please check the PR and merge it

**Comment by punyakrit** [comment]
@dhairyagothi i will check it soon

**Review by punyakrit — APPROVED** [review]

**Pull request merged**
