### PR TITLE
Created About Us page, Explore page and contact us page, fixed navbar issues

### PR DESCRIPTION
**Pull request by r7projects-shayan**
## PR Description

Closes Issue #5 #6 

## Tasks Implemented

Successfully done the following tasks- 

Created About Us page, Explore Page and Contact Us page

Fixed the Navbar responsiveness and Link issues

Fixed the Homepage not being responsive

Added transitions and attractive hover effects

## Screenshots

Screenshot 2024-06-04 204325
Screenshot 2024-06-04 204338
Screenshot 2024-06-04 204349
Screenshot 2024-06-04 204357
Screenshot 2024-06-04 204403
Screenshot 2024-06-04 204408
Screenshot 2024-06-04 204423
Screenshot 2024-06-04 204428
Screenshot 2024-06-04 204503
Screenshot 2024-06-04 204515
Screenshot 2024-06-04 204521
Screenshot 2024-06-04 204525
Screenshot 2024-06-04 204535
Screenshot 2024-06-04 204541
Screenshot 2024-06-04 204558
Screenshot 2024-06-04 204607
Screenshot 2024-06-04 204616
Screenshot 2024-06-04 204622
Screenshot 2024-06-04 204631

## Program

Gssoc 24

### CODE REVIEW

**Comment by punyakrit** [comment]
Hey can you remove appbar code its not aligned in design part , remove explore page doesn't look as thought , about looks fine just remove the core section part and contact us form also looks kinda weird according to design 
Screenshot 2024-06-04 at 10 27 04 PM
This sidebar is not required
Screenshot 2024-06-04 at 10 27 28 PM
Even this gloying effect

**Comment by r7projects-shayan** [comment]
@punyakrit Alright, I will change the contact form into a more simple one and do the changes you mentioned.

**Comment by r7projects-shayan** [comment]
@punyakrit Is the contact page fine now? Should I commit the changes?

Screenshot 2024-06-04 230937
Screenshot 2024-06-04 230942
Screenshot 2024-06-04 230956
Screenshot 2024-06-04 231000

**Comment by punyakrit** [comment]
just keep it simple like name email and textarea for details they want to share doesn't require specific map

**Comment by punyakrit** [comment]
could add a revolving globe

**Comment by r7projects-shayan** [comment]
@punyakrit Alright

**Comment by r7projects-shayan** [comment]
@r7projects-shayan I will raise the PR by tomorrow with the updates you asked for

**Comment by punyakrit** [comment]
sure

**Pull request merged**
